export const palette = {
  primary:      '#1A7A30',
  primaryHover: '#22A040',
  primaryLight: '#4DBB5A',
  muted:        '#1F5C2E',
  subtle:       '#4E8A58',
  icon:         '#4E8A58',
  leafAccent:   '#4DBB5A',
  white:        '#FFFFFF',
  background:   '#F2FAF4',
  surface:      '#FFFFFF',
  surfaceAlt:   '#E6F5EA',
  border:       '#9ED4A6',
  borderSubtle: '#C4E8CA',
  foreground:   '#0B2610',
  danger:       '#991B1B',
  dangerText:   '#991B1B',
} as const
